version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/lmattern/data/mariadb
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/lmattern/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
